[build]
  command = ""
  functions = "netlify/functions"

[functions.horoscopes]
  timeout = 26

[functions.sage]
  timeout = 26

[functions.invoke]
  timeout = 15

[[redirects]]
  from = "/for-models"
  to = "/"
  status = 301
  force = true
